### DISCUSSION TITLE
Is it possible to assign two different fonts for two different languages?

### DISCUSSION THREAD

**Discussion by Collapce** [jellyfin/jellyfin#10160] [Q&A] [answered]
I have libraries in differnt languages and was wandering if it was possible to assign a custom font for each languages using CSS, no idea how to go about it though,

I'm using something like this to assign one local custom font. I tried fonts that support multiple languages, but those have very limiting choises nad don't always look good in both languages.

```
@font-face { font-family: 'Freight Sans'; src:
url('https://www.domain.tld/web/fonts/freight_sans/freight_sans-medium.eot'); src:
url('https://www.domain.tld/web/fonts/freight_sans/freight_sans-medium.woff2') format('woff2'),
url('https://www.domain.tld/web/fonts/freight_sans/freight_sans-medium.woff') format('woff'),
url('https://www.domain.tld/web/fonts/freight_sans/freight_sans.ttf') format('truetype'); }
body, h1, h2, h3, h4 { font-family: 'Freight Sans', sans-serif; 
```

any ideas are appreciated. thank you.

**Comment by pypp** [comment, marked as answer]
You can achieve this using [unicode-range](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range).
something like this: 

```css

@font-face {
  font-family: font-1;
  src: ...;
  unicode-range: U+00-FF; /* Latin characters */ 
}

@font-face {
  font-family: font-2;
  src: ...;
  unicode-range: U+0590-05FF, U+FB1D-FB4F; /* Hebrew characters */
}
```

Another option is to define multiple font families like this :

```css
body {
  font-family: font-1, font-2;
}

```
