### DISCUSSION TITLE
Parental controls

### DISCUSSION THREAD

**Discussion by Darkhost1999** [jellyfin/jellyfin#10313] [Q&A]
I am a parent and I have a few questions.
In custom ratings.
Can I control what I see in the drop down menu so I can apply ratings easier. Such as Approved, Unapproved, and no Rating?
I don't believe Unapproved even exists. Why not?

More of a concern than a question -> my kid can bypass all restrictions by going to
Shows -> suggestions -> other tabs.
Movies -> suggestions -> other tabs.
Collection -> suggestions -> other tabs.
So chances are the only location parental controls is applied is library -> library tab and not anywhere else. This enables my kid to watch Unapproved titles and this is a huge issue imo.

Is a kids interface like Netflix an option anywhere. Can I set my kids profile to enable a kids zone interface? Not just disable admin but completely make this interface safe for a child that can't even read yet.

**Comment by Shadowghost** [comment]
To answer your questions generally:
What items are shown depends solely on the server, so it's client independent.

I would suggest waiting for 10.9 though since the current implementation is not reliably hiding all.content in all cases.

Custom ratings are not supported. We rely on the official age certifications which are mapped to a year equivalent to check access permissions between different rating systems.

**Comment by Darkhost1999** [comment]
Custom ratings work fine.
The ability to bypass parental controls does exist but my kid hasn't chosen to since the 1st day I posted this.
And my suggestion for a kid profile interface is still out there.

**Comment by TheMelmacian** [comment]
What Shadowghost meant with "custom ratings are not supported" is not that you can't set the rating yourself, but that only the currently available values can be set. If you set the rating, make sure to also disallow changes to the field at the end of the metadata editor, otherwise a refresh can revert the value.


>[...] Can I control what I see in the drop down menu so I can apply ratings easier. [...]

You can achieve this with custom CSS Rules: https://jellyfin.org/docs/general/clients/css-customization/

Specific values in the drop down can be hidden with the following rule:
```css
#selectOfficialRating option[value="<displayed-value>"] { display: none; }
```
for example:
```css
#selectOfficialRating option[value="TV-MA"] { display: none; }
#selectOfficialRating option[value="XXX"] { display: none; }
```

or you can hide all by default and explicitely show the values you want:
```css
#selectOfficialRating option { display: none; }
#selectOfficialRating option[value="TV-MA"] { display: inline !important; }
#selectOfficialRating option[value="XXX"] { display: inline !important; }
```


You could also use tags instead of the age rating. In contrast to the rating, you can add your own tags.
In the user settings you can then block access to specific tags.
