### DISCUSSION TITLE
Display Order: Aired (newest first)

### DISCUSSION THREAD

**Discussion by crchauffe** [jellyfin/jellyfin#11209] [General]
Hi, I've been looking for a way to sort seasons and episodes within a TV series by showing the most recent seasons and episodes first instead of the earliest seasons and episodes first.  

For example, I have several episodes of PBS NOVA from across several seasons:

![image](https://github.com/jellyfin/jellyfin/assets/3298281/25b7c359-0fd2-43a8-b6cd-3779c3e1fc81)

Season 51 is the season with the most recent airdate yet it appears last in the list of seasons.  I'd like to reverse this sorting so that Season 51 would appear first.

Furthermore, with this "most recent first" sorting enabled, I'd like for the most recent episodes to appear first within the season.  Currently, the sorting shows the most recent episodes last.

For example, this is what the current sorting looks like with several episodes of The Daily Show in season 29:

![image](https://github.com/jellyfin/jellyfin/assets/3298281/f48d2227-0404-444b-a61f-6117c6089cfb)

Ideally these would be sorted in reverse order as well.

How could this be achieved?  I've found the "display order" option under edit metadata, but the options don't really offer what I'm looking for.  When I modify the display order, the season and episode sorting don't seem to be affected.  Does anyone have any tips or tricks for this?

Thanks!

**Comment by sdylewski** [comment]
I'd love this too!  When we have 20 seasons, the latest one is always at the bottom, which is annoying to have to scroll down all the way to the bottom.  See South Park, for example also.

**Comment by TheMelmacian** [comment]
You can add your own custom css code to achieve this.
_server settings -> general_
or _user settings -> display_

```css
#itemDetailPage #childrenCollapsible #childrenContent .childrenItemsContainer.itemsContainer.vertical-list {
    flex-direction: column-reverse;
}
#itemDetailPage #childrenCollapsible #childrenContent .childrenItemsContainer.itemsContainer.vertical-wrap {
    flex-direction: row-reverse;
    flex-wrap: wrap-reverse;
    justify-content: start;
}
```

I only made a quick smoke test with these rules active and can't guarantee that no other pages besides the show and seasons views are affected.
