### DISCUSSION TITLE
Did the volume mappings change for 10.9?

### DISCUSSION THREAD

**Discussion by OddMagnet** [jellyfin/jellyfin#11290] [Q&A] [answered]
So I've set up 10.9 for testing like this:
1. Stop stable container
2. Copy and rename the folders containing it's configuration
3. Create and start the unstable container

I noticed that I had to go through the setup process again, which I thought was weird, but I pressed on.
Later during the "Chapter Image Extraction" task I noticed my servers Fans went crazy.
Jellyfin was creating thousands of collections.
So I checked the logs which were spammed with this:

> [2024-04-04 02:12:59.727 +02:00] [WRN] [66] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/collections" is inaccessible or empty, skipping
[2024-04-04 02:12:59.736 +02:00] [WRN] [66] MediaBrowser.Controller.Entities.BaseItem: Library folder "/config/data/playlists" is inaccessible or empty, skipping
[2024-04-04 02:13:14.000 +02:00] [ERR] [125] Emby.Server.Implementations.Library.Validators.CollectionPostScanTask: Error refreshing "The Wolverine Collection" with [13d32704-ccc9-1f16-1112-cdfd042db9d7, e296abff-32e0-7471-c030-85762ee863ce, 25ecddeb-4dc9-e1e5-041d-04c7b1f6be96]

Checking via `docker exec -it jellyfin-unstable bash`, here's the `tree` of my folder structure:

```shell
.
├── bin -> usr/bin
├── boot
├── cache
│   ├── chapter-failures.txt
│   ├── images
│   ├── omdb
│   ├── temp
│   └── transcodes
├── config/
│   ├── branding.xml
│   ├── cache
│   │   ├── chapter-failures.txt
│   │   └── ...
│   ├── config
│   │   ├── branding.xml
│   │   ├── encoding.xml
│   │   ├── logging.default.json
│   │   ├── migrations.xml
│   │   ├── network.xml
│   │   └── system.xml
│   ├── data
│   │   ├── collections # <-- this one is empty
│   │   ├── data 
│   │   │   └── collections # <-- actual collections are here
│   │   ├── device.txt
│   │   ├── jellyfin.db
│   │   ├── jellyfin.db-shm
│   │   ├── jellyfin.db-wal
│   │   ├── keyframes
│   │   ├── library.db
│   │   ├── library.db-shm
│   │   ├── library.db-wal
│   │   ├── metadata
│   │   ├── playlists
│   │   ├── plugins
│   │   ├── root
│   │   ├── ScheduledTasks
│   │   ├── splashscreen.png
│   │   ├── subtitles
│   │   └── transcodes
│   ├── dlna/...
│   ├── encoding.xml
│   ├── log/...
│   ├── logging.default.json
│   ├── metadata/...
│   ├── migrations.xml
│   ├── network.xml
│   ├── plugins/...
│   ├── root/...
│   └── system.xml
├── data
│   └── media
├── dev/...
├── etc/...
├── home
├── jellyfin/...
├── lib -> usr/lib
├── lib64 -> usr/lib64
├── mail
├── media
├── mnt
├── opt
├── proc/...
├── root
├── run/lock
├── sbin -> usr/sbin
├── srv
├── sys/...
├── tmp/...
├── usr/...
└── var/...
``` 

Here are my compose files, for stable:
```
services:
   jellyfin:
     container_name: jellyfin
     image: lscr.io/linuxserver/jellyfin:${JELLYFIN_VERSION}
     restart: unless-stopped
     volumes:
       - ${CONFIG_DIR}/jellyfin:/config
       - ${MEDIA_DIR}:/data/media
     devices:
       - '/dev/dri:/dev/dri'
``` 

and unstable:
```
services:
  jellyfin-unstable:
    container_name: jellyfin-unstable
    image: jellyfin/jellyfin:unstable
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/jellyfin-unstable:/config
      - ${MEDIA_DIR}:/data/media
    devices:
      - '/dev/dri:/dev/dri'
```
