### ISSUE TITLE
[Issue]: lstat /proc/10788/ns/net: no such file or director

### ISSUE THREAD

**Issue by Compr0mzd** [jellyfin/jellyfin#10497]
### Please describe your bug

```
Started Container jellyfin Started Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to create new parent process: namespace path: lstat /proc/10788/ns/net: no such file or directory: unknown
 ```
I'm trying to start jellyfin container and mount the media volume as a SMB storage on a Hetzner Storage Box however I always get the error above. I have no idea what could cause this issue.
Below the docker compose configuration : 
```
jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - media-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - media-stack-torrents:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    restart: unless-stopped
volumes:
  media-stack-torrents:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /mnt/storage-box
```

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Debian 11
- Linux Kernel: 5.10.0-26-amd64
- Virtualization: Docker w Portainer
- Clients: /
- Browser: /
- FFmpeg Version: / 
- Playback Method: / 
- Hardware Acceleration: / 
- GPU Model: /
- Plugins: / 
- Reverse Proxy: / 
- Base URL: / 
- Networking: / 
- Storage: cifs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
