### ISSUE TITLE
[help] Poor Transcode Performance on DS423+ using JF with Intel QSV transcoding one stream

### ISSUE THREAD

**Issue by bradleycundari** [jellyfin/jellyfin#10690]
**Media Info of the file**
![info](https://github.com/jellyfin/jellyfin/assets/8679059/ef9e21ca-908f-4216-9570-6a8b7bfb1933)

**Logs**
[Log.txt](https://github.com/jellyfin/jellyfin/files/13592263/Log.txt)

**FFmpeg Logs**
[transcode log.txt](https://github.com/jellyfin/jellyfin/files/13592265/transcode.log.txt)

**Stats for Nerds Screenshots**
![system usage](https://github.com/jellyfin/jellyfin/assets/8679059/9c061677-86c4-42c8-ba47-cd6ec5946117)

**Server System (please complete the following information):**
 - OS: Docker on Linux/Synology
 - Jellyfin Version: Latest on Linux Server Image
 - Hardware settings & device: intel qsv
 - Reverse proxy: synology reverse proxy
 - Other hardware notes: 
```
DS423+ expanded RAM with 16gb CT16G4SFRA266
Volume 1: 18TBx4 Seagate Exos X20 ST180000NM003D
Volume 1 Read Only Cache: 4 TB - TEAMGROUP MP 34 m.2
Volume 2: 4 TB - TEAMGROUP MP34 m.2
```
 
**Client System (please complete the following information):**
 - Device: LG B2
 - OS: LGOS
 - Client: JellyFin
 Poor performance regardless of client
 
 
 Container params:
 ```
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1028 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=America/New_York #CHANGE_TO_YOUR_TZ
      - UMASK=022
      - JELLYFIN_PublishedServerUrl=192.168.0.119
    volumes:
      - /volume2/docker/jellyfin:/config
      - /volume1/data/media:/data/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 8096:8096 #web port
      - 8920:8920 #optional
      - 7359:7359/udp #optional
    network_mode: synobridge
    security_opt:
      - no-new-privileges:true
    restart: always
```
