### ISSUE TITLE
Downloading 2 subtitle files of the same language throws an exception "already exists"

### ISSUE THREAD

**Issue by zjeffer** [jellyfin/jellyfin#10696]
**Steps to reproduce:**

1. Download a subtitle file
2. Download another subtitle file of the same language
3. They will both try to be saved as the same filename, this throws an error:

```
<first download, this one is successful>
jellyfin  | [22:19:35] [INF] [9] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 990
jellyfin  | [22:19:35] [INF] [27] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt

<second download of a different file, it saves it to the same name:>
jellyfin  | [22:20:00] [INF] [9] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 989
jellyfin  | [22:20:00] [INF] [7] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt
jellyfin  | [22:20:00] [INF] [7] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt
jellyfin  | [22:20:00] [ERR] [7] Jellyfin.Api.Controllers.SubtitleController: Error downloading subtitles
jellyfin  | System.AggregateException: One or more errors occurred. (The file '/media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.) (The file '/config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.)
jellyfin  |  ---> System.IO.IOException: The file '/media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.
jellyfin  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.FileStream..ctor(String path, FileStreamOptions options)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)
jellyfin  |    --- End of inner exception stack trace ---
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
jellyfin  |    at Jellyfin.Api.Controllers.SubtitleController.DownloadRemoteSubtitles(Guid itemId, String subtitleId)
jellyfin  |  ---> (Inner Exception jellyfin/jellyfin-plugin-opensubtitles#1) System.IO.IOException: The file '/config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.
jellyfin  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.FileStream..ctor(String path, FileStreamOptions options)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)<---
```

**Expected behavior:** 
The 2nd subtitle file should also be downloaded, but be saved with something like `<mediafile-name>.<language>.<number>.srt` as the filename.

**Setup:**
Running in docker:

```
version: '3.5'
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
      - "8920:8920"
    networks:
      - proxy
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /media/pi/Elements:/media
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    mem_limit: 1200M
    memswap_limit: 512M
  
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - "proxy"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

networks:
  proxy:
    driver: bridge

volumes: # these lines are necessary for creating the volumes
  jellyfin-config:
  jellyfin-cache:
  caddy_data:
  caddy_config:
```
