### ISSUE TITLE
Error message "This client isn't compatible with the media and the server isn't sending a compatible media format" is wrong and extremely misleading

### ISSUE THREAD

**Issue by veqryn** [jellyfin/jellyfin#10778]
Attempting to play an mkv h264 video on an older tablet gives "This client isn't compatible with the media and the server isn't sending a compatible media format".
This exact video plays just fine on other devices, including my phone (android app) and my laptop (mac).
However, it won't play on my tablet (android, details below).
The tablet will play other videos though, so I am wondering why jellyfin won't just transcode to a video format that works for this tablet.

This is on a brand new and very simple, non-customized linux-container-based install of Jellyfin.  No plugins installed except whatever comes with Jellyfin by default.

**Media Info of the file**
1080i H264 SDR

<details>

```text
Blue Planet II (2017) - S01E01 - One Ocean [Bluray-1080p Remux][AC3 2.0][AVC]-FraMeSToR
Container: mkv
Path: /tv-series/Blue Planet II (2017)/Season 1/********.mkv
Size: 14139 MB

Video
Title: 1080i H264 SDR
Codec: H264
AVC: Yes
Profile: High
Level: 41
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: Yes
Framerate: 25
Bitrate: 34160 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p
Ref frames: 1
NAL: 4

Audio
Title: Н. Дроздов + Jimmy J. - Russian - Dolby Digital - Stereo - Default
Language: rus
Codec: AC3
Layout: stereo
Channels: 2 ch
Bitrate: 384 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Audio
Title: Jimmy J. - Russian - DTS - 5.1
Language: rus
Codec: DTS
Profile: DTS
Layout: 5.1
Channels: 6 ch
Bitrate: 1536 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: ColdFilm - Russian - Dolby Digital - Stereo
Language: rus
Codec: AC3
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: English - DTS-HD MA - 5.1
Language: eng
Codec: DTS
Profile: DTS-HD MA
Layout: 5.1
Channels: 6 ch
Bitrate: 2264 kbps
Sample rate: 48000 Hz
Bit depth: 16 bit
Default: No
Forced: No
External: No

Subtitle
Title: English - SUBRIP
Language: eng
Codec: SUBRIP
Default: No
Forced: No
External: No

Subtitle
Title: English - PGSSUB
Language: eng
Codec: PGSSUB
Default: No
Forced: No
External: No

Subtitle
Title: Chi - SUBRIP - External
Language: chi
Codec: SUBRIP
Default: No
Forced: No
External: Yes
```

</details>

**Logs**
There were no useful or related logs generated on the server when the client tried to access the video.  I don't see how to get client logs for the android app.  Below are what logs were on the server during the time I clicked the video.

<details>

```text
2023/12/29 01:04:46,stdout,[01:04:46] [WRN] [28] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://****Items/8408e6dda89fb0c95c3fb8987ccc80ea/Images/Backdrop/0?tag=911d33527f8723ef7d61c924171a85f1&maxWidth=3840&quality=80 to 172.20.0.1 in 0:00:00.6014388 with Status Code 200

2023/12/29 01:03:39,stdout,[01:03:39] [INF] [16] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was forbidden.

2023/12/29 01:03:21,stdout,[01:03:21] [INF] [33] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.

2023/12/29 01:03:09,stdout,[01:03:09] [INF] [42] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.

2023/12/29 01:02:45,stdout,[01:02:45] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://****/Items/b05c3d958fba5aeef82e3a06b68f981b/Images/Backdrop/0?tag=7e233750e5d178aa05c8d2bcf341ed17&maxWidth=3840&quality=80 to 172.20.0.1 in 0:00:00.6706503 with Status Code 200

2023/12/29 01:01:30,stdout,[01:01:30] [INF] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was forbidden.
```

</details>

**FFmpeg Logs**
No FFmpeg logs were generated around the time I clicked to play the video.

**Stats for Nerds Screenshots**
Not sure where that is. 

**Server System (please complete the following information):**
 - OS: Synology 7.2 running Docker version 20.10.23, build 876964a, on a Synology 920+ NAS.
 - Jellyfin Version: 10.8.13
 - Hardware settings & device: Synology 920+
 - Reverse proxy: no
 - Other hardware notes: Media is colocated on the same drive, and mounted in read-only
docker-compose:

<details>

```yaml
services:
  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: lscr.io/linuxserver/jellyfin:10.8.13-1-ls240
    ports:
      # ui
      - 58096:8096
      - 58920:8920
      - 7359:7359/udp
    environment:
      - PUID=1027
      - PGID=100
      - TZ=America/Denver
      - JELLYFIN_PublishedServerUrl=****
    devices: 
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /volume1/****/config:/config
      - /volume1/****:/data/****:ro
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - media
```

</details>

The only configuration/setup made was the initial setup walkthrough, adding a children's account that doesn't have a password, and turning on hardware acceleration (VAAPI), and then rebooting the docker-compose.
 
**Client System (please complete the following information):**
 - Device: Samsung Tab A 8.0, Model SM-T350 (2015)
 - OS: Android 7.1.1, Samsung UI 8.5
 - Client: Android App, version 2.6.0 (fully up-to-date with google play)
