### ISSUE TITLE
[Issue]: 502 Bad Gateway and reverse dns on docker

### ISSUE THREAD

**Issue by neckva** [jellyfin/jellyfin#10831]
### Please describe your bug

hello
I'm new to Docker. I followed the Nextcloud installation [tutorial](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml), with in particular this part which interests us: 
```
  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:z,ro
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/tmp/docker.sock:z,ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: nginxproxy/acme-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs:z
      - acme:/etc/acme.sh:z
      - vhost.d:/etc/nginx/vhost.d:z
      - html:/usr/share/nginx/html:z
      - /var/run/docker.sock:/var/run/docker.sock:z,ro
    networks:
      - proxy-tier
    depends_on:
      - proxy
```
On the other hand, I installed jellyfin like this:
```
  sudo docker run -d \
  --name=jellyfin \
  -e PUID=33 \
  -p 8096:8096 \
  -e PGID=33 \
  -e TZ=Europe/Paris \
  -e VIRTUAL_HOST=cine.mywebsite.com\
  -e LETSENCRYPT_HOST=cine.mywebsite.com \
  -e LETSENCRYPT_EMAIL=vaneck@mywebsite.com \
  -v /home/vaneck/jellyfin:/config \
  -v /home/vaneck/jellyfin/cache:/cache \
  -v /mnt/ncdata/nextcloud:/media \
  --network=nextcloudfinal_proxy-tier \
  --restart unless-stopped \
  lscr.io/linuxserver/jellyfin:latest
```
And although I can connect to the localhost:8096, I can't get to cine.mywebsite.com. I've got a wonferfull **502 Bad Gateway**
I think there's something on jellyfin that blocks reverseDns. I did specify this in network: 
Proxies connus (know proxie i guess) : cine.mywebsite.com, 172.18.0.3 (ip of the contener reverse dns)
Do you have any idea where to start?
thanks

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS:ubuntu 22.04
- Browser:firefox
- Reverse Proxy:nginx
- Base URL:cine.mywebsite.com
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
