### ISSUE TITLE
[Issue]: Migrating docker jellyfin with data to new server not working

### ISSUE THREAD

**Issue by blade1989** [jellyfin/jellyfin#11007]
### Please describe your bug

My server crashed, managed to copy the config/ and cache/ directories to a new server.

On the new server, I used the same docker compose file, and it works for a moment, after that, it starts deleting the folders from the database?

# docker-compose

```yaml
version: "2"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: always
    network_mode: 'host'
    environment:
      - JELLYFIN_PublishedServerUrl=[REDACTED]
    volumes:
      - ./config:/config
      - /path/to/Media:/Media
      - ./cache:/cache
```

### Reproduction Steps

 copy the config and cache directory to a new server, use the same `docker-compose` to start up jellyfin.

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
- Linux Kernel: 5.15.0-94-generic
- Virtualization: docker
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
...
jellyfin  | [10:16:20] [INF] [8] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /Media/Movies
...
jellyfin  | [10:17:19] [INF] [33] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path /Media/Movies
...
jellyfin  | [10:18:09] [INF] [33] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Folder, Name: Movies, Path: /Media/Movies, Id: 601b09af-ea4e-7495-7a6a-0e5b07aed01e
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
