### ISSUE TITLE
[Issue]: 10.9.2 DLNA Plug 1.0.0.0 seems not working

### ISSUE THREAD

**Issue by andreascschmidt** [jellyfin/jellyfin#11791]
### Please describe your bug

I have the Jellyfin docker version and just updated to 10.9.2 and installed the now separate DLNA plugin. 
restarted the server, but neither do I see devices under send to devices, not do I see in VLS or other DLNA tools the Jellyfin server. 

### Reproduction Steps

docker-compose
```
version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: host # Enable DLNA and Wake-on-Lan
    volumes:
      - ./config:/config # Configuration directory
      - ./cache:/cache
      - /share/CACHEDEV2_DATA/ZMultimedia:/mnt/Jdownloader # Media directory
      - /share/CACHEDEV2_DATA/Backups:/mnt/Backups # Media directory
      - /share/NFSv=4/Dropbox-Gateway:/mnt/Dropbox # Media directory
    restart: always
```

in the logs I see only
```
log_20240522.log:[2024-05-22 10:38:46.432 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Dlna.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/DLNA_1.0.0.0/Jellyfin.Plugin.Dlna.Model.dll"
log_20240522.log:[2024-05-22 10:38:53.071 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "DLNA" "1.0.0.0"
log_20240522.log:[2024-05-22 10:38:53.977 +00:00] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "127.0.0.1"
log_20240522.log:[2024-05-22 10:38:54.042 +00:00] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.1.5"
log_20240522.log:[2024-05-22 10:38:54.054 +00:00] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "172.29.4.1"


I have at least 2 streaming consumers in the network and it worked fine a few weeks ago.
```

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
log_20240522.log:[2024-05-22 10:38:46.432 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Dlna.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/plugins/DLNA_1.0.0.0/Jellyfin.Plugin.Dlna.Model.dll"
log_20240522.log:[2024-05-22 10:38:53.071 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "DLNA" "1.0.0.0"
log_20240522.log:[2024-05-22 10:38:53.977 +00:00] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "127.0.0.1"
log_20240522.log:[2024-05-22 10:38:54.042 +00:00] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.1.5"
log_20240522.log:[2024-05-22 10:38:54.054 +00:00] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "172.29.4.1"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
