### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by prabhu-madanagopal** [jellyfin/jellyfin#12997]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

After upgrading to 10.10.1, the server does not start due to ffmpeg error.
The error is not very specific, I tried upgrading the jellyfin-ffmpeg version in openmediavault to 7.0.2-Jellyfin, but the issue is the same.
Attaching the logs.
[Jellyfin Log from OpenMediaVault.log](https://github.com/user-attachments/files/17686082/Jellyfin.Log.from.OpenMediaVault.log)

```
jellyfin  | [20:50:26] [ERR] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg validation: The process returned no result
jellyfin  | [20:50:26] [ERR] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Failed version check: /usr/lib/jellyfin-ffmpeg/ffmpeg
jellyfin  | [20:50:26] [ERR] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: Path set by command line or environment variable is invalid
jellyfin  | [20:50:26] [FTL] [1] Main: Error while starting server
jellyfin  | MediaBrowser.Common.FfmpegException: Failed to find valid ffmpeg
jellyfin  |    at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
jellyfin  |    at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)
```

### Reproduction steps

1. Setup OpenMediaVault
2. Install Compose plugin to run docker containers in OMV
3. Install Jellyfin ffmpeg 7 in omv to the same user that you use in the docker container
4. Install Jellyfin server using the below compose file

```
---
# https://hub.docker.com/r/linuxserver/jellyfin
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles

    security_opt: # enables full access to /sys and /proc, still far better than privileged: true
      - systempaths=unconfined
      - apparmor=unconfined
    group_add:
      - video
    devices:
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      - /dev/mali0:/dev/mali0 # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    volumes:
      - /etc/OpenCL:/etc/OpenCL:ro # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
      - /usr/lib/aarch64-linux-gnu/libmali.so.1:/usr/lib/aarch64-linux-gnu/libmali.so.1:ro # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
      - /usr/lib/jellyfin-ffmpeg:/usr/lib/jellyfin-ffmpeg
      - /usr/lib/aarch64-linux-gnu/libx264.so.164:/usr/lib/aarch64-linux-gnu/libx264.so.164
      - ${PATH_TO_APPDATA}/jellyfin/library:/config
      - ${PATH_TO_DATA}/media/tvseries:/data/tvshows
      - ${PATH_TO_DATA}/media/movies:/data/movies
      - ${PATH_TO_DATA}/media/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

```

### What is the current _bug_ behavior?

The server keeps bouncing with the error in the log attached to description.

### What is the expected _correct_ behavior?

Server starts sucessfully and I can reach it from browser.

### Jellyfin Server version

10.10.0+

### Specify the build version

Cannot go to dashboard

### Environment

```markdown
- OS:Open Media Vault 7.4.11-1 (Sandworm)
- Linux Kernel:
- Virtualization:Docker
- Clients:
- Browser:
- FFmpeg Version:7.0.2-Jellyfin 
- Playback Method:
- Hardware Acceleration:RKMPP
- GPU Model:Rockchip RK3588
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
Attached
```

### FFmpeg logs

```shell

```
