### ISSUE TITLE
Transcoding is crashing with Intel HD Graphics 500 iGPU

### ISSUE THREAD

**Issue by adamradocz** [jellyfin/jellyfin#13062]
I have an Intel HD Graphics 500 iGPU (Gen9 - Appolo Lake).

The official docker (version 10.10.2) says "Playback issue" when I try to transcode a video.
Although, the linuxserver/jellyfin version works perfectly with exactly the same configuration.

The compose looks like this:
```
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: ${PUID}:${PGID}
    env_file: stack.env
    environment:
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://${HOST_ADDRESS} #optional
    volumes:
      - ${APPDATA_PATH}/Jellyfin/config:/config
      - ${MEDIA_PATH}:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```
