### ISSUE TITLE
Live TV/HDHomeRun Flex 4K - Certain Channels Don't Play

### ISSUE THREAD

**Issue by HouseIndoril** [jellyfin/jellyfin#13200]
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

I have 2 Jellyfin servers, one on Docker (lscr.io image, host is Ubuntu 22.04) and the other on the bare metal (Ubuntu 22.04). I've added my HDHomeRun tuner to both of them. Both are on 10.10.3. 

When I attempt to watch the one channel I care to watch (everyone's got that one show they like), the docker server refuses to play it every time, but the server on bare metal plays it flawlessly. 

The docker server is set up in Host mode according to [the instructions](https://jellyfin.org/docs/general/server/live-tv/). 

### Reproduction steps

1. Log in to the bare metal server. 
2. Attempt to play the channel 10.1
3. It works flawlessly
4. Repeat steps 1-2 on the docker server
5. It fails. 

### What is the current _bug_ behavior?

The channel does not play. 

### What is the expected _correct_ behavior?

The channel should play. 

### Jellyfin Server version

10.10.0+

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Ubuntu 22.04 
- Linux Kernel:5.15
- Virtualization: Docket
- Clients: Android, LG WebOS, 
- Browser: Firefox
- FFmpeg Version: 7.0.2-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: QSV/VAAPI
- GPU Model: Intel HD 630 (10th Gen iGPU)
- Plugins:
- Reverse Proxy: N/A on bare metal, Caddy on Docker, but issue is present when skipping reverse proxy as well. 
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs
[jellyfin_log_baremetal.txt](https://github.com/user-attachments/files/18070700/jellyfin_log_baremetal.txt)
[jellyfin_log_docker.txt](https://github.com/user-attachments/files/18070701/jellyfin_log_docker.txt)

### FFmpeg logs
[jellyfin_ffmpeg_baremetal.txt](https://github.com/user-attachments/files/18070719/jellyfin_ffmpeg_baremetal.txt)
[jellyfin_ffmpeg_docker.txt](https://github.com/user-attachments/files/18070718/jellyfin_ffmpeg_docker.txt)

### Relevant screenshots or videos

![Image](https://github.com/user-attachments/assets/0150c29f-4ea8-46ee-8a11-f417b2275411)
![Image](https://github.com/user-attachments/assets/0d81d85f-ea56-4067-a428-594c0cb1edba)

### Additional information

Other channels, such as 4.1 and 6.1 on the docker server play without issue.

**Comment by HouseIndoril** [comment]
Docker compose file 
```
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=115
      - PGID=120
      - TZ=America/New_York
    network_mode: 'host'
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - type: bind
        source: /media/Jellyfin_Library/Movies
        target: /data/movies
      - type: bind
        source: /media/Jellyfin_Library/TV
        target: /data/tv
      - type: bind
        source: /media/Jellyfin_Library/Recordings
        target: /data/recordings
      - type: bind
        source: /media/Jellyfin_Library/Personal Media
        target: /data/personal media
      - type: bind
        source: /media/disk2/transcodes
        target: /data/transcodes
    #ports:
     # - 8096:8096
    restart: 'unless-stopped'
```
