### ISSUE TITLE
Cannot connect to server behind reverse proxy after upgrade to 10.10.7 - /system/info/public returns http 503

### ISSUE THREAD

**Issue by michag86** [jellyfin/jellyfin#13954]
### Description of the bug

After upgrading from 10.10.6 to 10.10.7 it is not possible to connect to jellyfin.
I have a setup where jellyfin is behind traefik.

Here is my compose.yml
```
services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.7
    container_name: jellyfin
    hostname: jellyfin
    user: 1000:1000
    group_add:
      - "105"
    network_mode: 'host'
    volumes:
      - [...]
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: always
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.1:8096/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadBalancer.server.port=8096"
      - 'traefik.http.services.jellyfin.loadBalancer.passHostHeader=true'
```

With 10.10.6 this was working without problems.

### Reproduction steps

Setup jellyfin behind reverse proxy (with traefik and docker-compose from above).

### What is the current _bug_ behavior?

/system/info/public returns http 503
Message is shown: "Wir können gerade keine Verbindung zum gewählten Server herstellen. Bitte stelle sicher, dass dieser läuft und versuche es erneut."

After enabling debug log, I can see this in the debug log:
jellyfin    | 2025-04-20T12:23:50.017477000Z [12:23:50] [INF] [23] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://jellyfin.localdomain.loc/system/info/public - null null
jellyfin    | 2025-04-20T12:23:50.017782000Z [12:23:50] [INF] [23] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 GET http://jellyfin.localdomain.loc/system/info/public - 503 0 null 0.4878ms

Login with http on mapped port 8096 works.

### What is the expected _correct_ behavior?

Connect works with and without reverse proxy.

### Jellyfin Server version

10.10.0+

### Specify version number

10.0.7

### Specify the build version

10.10.7

### Environment

```markdown
- OS: Debian Bookworm
- Linux Kernel: 6.1.0-32-amd64
- Virtualization: Docker
- Clients: doesn't matter
- Browser: doesn't matter
```

### Jellyfin logs

```shell
[2025-04-20 12:23:33.154 +00:00] [INF] [25] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting "HTTP/1.1" "GET" "http"://"jellyfin.localdomain.loc"""/System/Info/Public""" - null null
[2025-04-20 12:23:33.160 +00:00] [INF] [25] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished "HTTP/1.1" "GET" "http"://"jellyfin.localdomain.loc""""/System/Info/Public""" - 503 0 null 6.6553ms
```

### FFmpeg logs

```shell

```
