### ISSUE TITLE
system/server/info/public request has massive timeout/fails.

### ISSUE THREAD

**Issue by grimkor** [jellyfin/jellyfin#2169]
**Describe the bug**

With docker images from jellyfin and linuxserver on x86:

When loading the application in the browser the `https://example.com/system/info/public` takes a long time to resolve, leaving the application in a loading state. Eventually the site will be presented and the request will still not have resolved.

This also prevents the Android application from making a connection with the server.

Blocking the URL through Firefox Development Tools proves this endpoint to be the issue as the page will instead load instantaneously.

**To Reproduce**
1. Launch docker container, example of docker-compose below:
```
version: "3.4"
services:
  app:
    image: jellyfin/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - /path_to/jellyfin/config:/config
      - /path_to/jellyfin/cache:/cache
      - /path_to/jellyfin/files/Music/:/media:ro
      - /path_to/jellyfin/transcoding:/transcode #optional
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
```
2. Open browser developer console and go to network tab
3. Go to http://\<URL>:8096/
4. Observe the "public" XHR request

**Expected behavior**

To resolve the request in a timely manner.

**Logs**

**System (please complete the following information):**
 - OS: Docker in Debian 9
 - Browser: Tested in all browsers, mobile app cannot connect to server
 - Jellyfin Version: 10.4.1 (latest)
 - Installed Plugins: None
 - Reverse proxy: Traefik, tried without traefik and connecting directly to IP address:port and still get the same issue

**Additional context**

None
