### ISSUE TITLE
docker user permission for transcoding

### ISSUE THREAD

**Issue by Ashyni** [jellyfin/jellyfin#2281]
**Describe the bug**
Running the container with another user than root like `--user 1000:1000` doesn't create the appropriate user and group needed to access the device.
```
crw-rw---- root video /dev/dri/card0
crw-rw---- root 131 /dev/dri/renderD128
```

**Logs**
```
`[AVHWDeviceContext @ 0x562f58a85d40] No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument`
```

**Possible Fix**
Running /bash as root, adding the user and group inside the container, not enough to make it work.
```
useradd -u 1000 abc
groupadd -r -g 131 render
usermod -aG render abc
```
I only try the same command found in the log,
`/usr/local/bin/ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi -vaapi_device /dev/dri/renderD128 ...`
 It's working as root, no idea how to restart jellyfin inside docker to properly test it.

**System (please complete the following information):**
 - OS: Docker jellyfin/jellyfin:latest
 - Jellyfin Version: 10.4.3

**Comment by PrplHaz4** [comment]
> It's working as user 1000, no idea how to restart jellyfin inside docker to properly test it.
> 

Kill the dotnet process inside the container to automatically restart Jellyfin. 
`kill -15 6`

**Comment by Ashyni** [comment]
Just try and it's actually not working with user 1000, root is ok.
> useradd -u 1000 abc
groupadd -r -g 131 render
usermod -aG render abc
This is not enough, no idea what's missing, i have the same perm on host and inside container.
`abc : abc render video`
Maybe more Capabilities are required, i will try tomorrow.

**Comment by FrouxBY** [comment]
You might want to see how https://github.com/linuxserver/docker-jellyfin do it

**Comment by Ashyni** [comment]
`id` return after adding user/group/mod:
`uid=1000(abc) gid=1000(abc) groups=1000(abc),131(render)` // abc or 1000
`uid=1000(abc) gid=1000(abc) groups=1000(abc)` // default user
Running /bash with `abc` or `1000` allow to use the device but not with `default user`.
Restarting with `kill -15 6`, doesn't seems to refresh every perms/groups.

**Comment by Artiume** [comment]
so i dont have vaapi so i cant test it, but can you try a new container and just add user 1000 to the video group? no creation of user abc.

**Comment by Ashyni** [comment]
Hello, i switch to nvidia a week ago.
But to answer, we can't add directly a user that doesn't exist to a group
`usermod -aG video 1000`
`usermod: user '1000' does not exist`
Anything can be done before the entrypoint.

Like FrouxBY mention :
> You might want to see how https://github.com/linuxserver/docker-jellyfin do it

**Comment by xternaal** [comment]
From what I can see I think this issue occurs because the image uses "video" as the group for renderD128 where as the group is render on ubuntu distributions.

When you go into bash inside the shell the group is unrecognised or maps to video. I have fixed it by setting the host group for renderD128 to video or setting the permissions to  777 (v. bad idea i assume). 

However the user group for renderD128 reverts to render on every reboot

**Comment by Artiume** [comment]
Until it's fixed upstream in our code, you can run a startup script similar to this https://github.com/linuxserver/docker-jellyfin/issues/26#issuecomment-618089750

It still needs to be fixed upstream but hopefully this help

**Comment by christian-titze** [comment]
I just had the same problem and couldn't narrow it down to a permissions issue. If anyone stumbles upon this thread, chances are you made the same dumb mistake I made: Make sure that you've mounted `/dev/dri/` **as a device and not as a volume**! (and make sure the user of your jellyfin container is in the `render` group).

Works like a charm now on an Ubuntu 20.04 server with docker-compose. Here's an example of my working `docker-compose.yml` file:

```
version: "2" # We need v2 because of https://github.com/docker/compose/issues/3328
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    user: "113:65534" # 113 is the id of the 'jellyfin' user on my host, 65534 is 'nogroup'
    group_add:
      - "109" # 109 is the id of the 'render' group on my host
    network_mode: host
    ports:
      - 8096:8096/tcp
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /path/to/media:/media
```

Additional information about my setup:
```
user@host$ id jellyfin
uid=113(jellyfin) gid=65534(nogroup) groups=65534(nogroup),44(video),109(render)

I have no name!@jellyfin:/$ id
uid=113 gid=65534(nogroup) groups=65534(nogroup),109

user@host$ ls -lh /dev/dri
crw-rw---- 1 root video  226,   0 Jun 14 21:49 card0
crw-rw---- 1 root render 226, 128 Jun 14 21:49 renderD128

I have no name!@jellyfin:/$ ls -lh /dev/dri
crw-rw---- 1 root video 226,   0 Jun 14 19:50 card0
crw-rw---- 1 root   109 226, 128 Jun 14 19:50 renderD128
````
