### ISSUE TITLE
Media Player Controls Enhancement - Repeat Toggle

### ISSUE THREAD

**Issue by mitchelljfranklin** [jellyfin/jellyfin#2419]
Hi All,

Was wondering if the below enhancement would be possible to be made? currently when in device mode (Mobile / max width smaller then 47em) some of the controls are hidden to provide a better view; one of these is the Repeat Button Toggle; not sure about others but it is something I use often and believe it should be a visible control; under src/components/remotecontrol/remotecontrol.css at line 227 if the following is removed and or commented out this enables the repeat toggle to be made visible.

```css
@media all and (max-width: 47em) {
    .nowPlayingInfoButtons .repeatToggleButton {
        display: none !important;
    }
}
```
please let me know if this is something that would be considered :)

Ta

Mitch
