### ISSUE TITLE
Sonarr not updating

### ISSUE THREAD

**Issue by dannymichel** [jellyfin/jellyfin#2487]
I created a sonarr 'connection' and when new episodes are added i see 
```
[2020-02-29 16:43:40.269 -05:00] [DBG] [] LibraryMonitor: New file refresher created for "/mnt/mergerfs/media/tv/When They Cry - Higurashi"
[2020-02-29 16:45:26.148 -05:00] [DBG] [] LibraryMonitor: Timer stopped.
```
in the logs and the episodes aren't actually added.

**Comment by lelamamalgache** [comment]
do you have the path on sonarr and jellyfin "/mnt/mergerfs/media/tv" ?

**Comment by hayer** [comment]
Please check the path as @lelamamalgache mentioed. If they are different cause of how you've mapped the drives add a [remote path mapping](https://github.com/Radarr/Radarr/wiki/Remote-Path-Mappings-explained).

**Comment by dannymichel** [comment]
> Please check the path as @lelamamalgache mentioed. If they are different cause of how you've mapped the drives add a [remote path mapping](https://github.com/Radarr/Radarr/wiki/Remote-Path-Mappings-explained).

you're right

**Comment by dannymichel** [comment]
the issue though is that the jellyfin docker has ``/mnt/mergerfs/media`` as ``/media`` and sonarr, radarr, lidarr, and rutorrent have ``/mnt/mergerfs/media`` as ``/data/media``
Remote path mapping wouldnt work for me because of how i have the docker containers @hayer 
```
version: '3'

services:
  jackett:
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - '9117:9117'
    volumes:
      - '/data/jackett/:/config'
    restart: unless-stopped
    image: linuxserver/jackett

  rutorrent:
    container_name: rutorrent
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '8080:80'
      - '444:443'
      - '5000:5000'
      - '51413:51413'
      - '6881:6881/udp'
    volumes:
      - '/data/rutorrent/:/config'
      - '/mnt/mergerfs/:/data'
    restart: unless-stopped
    image: linuxserver/rutorrent

  radarr:
    container_name: radarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    ports:
        - '7878:7878'
    volumes:
      - '/data/radarr:/config'
      - '/mnt/mergerfs/:/data'
    restart: unless-stopped
    image: 'linuxserver/radarr:preview'

  sonarr:
    container_name: sonarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    ports:
      - '8989:8989'
    volumes:
      - '/data/sonarr:/config'
      - '/mnt/mergerfs/:/data'
    restart: unless-stopped
    image: 'linuxserver/sonarr:preview'

  lidarr:
    container_name: lidarr
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    ports:
      - '8686:8686'
    volumes:
      - '/data/lidarr:/config'
      - '/mnt/mergerfs/:/data'
    restart: unless-stopped
    image: 'linuxserver/lidarr:preview'

  nzbget:
    container_name: nzbget
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    ports:
      - '6789:6789'
    volumes:
      - '/data/nzbget:/config'
      - '/mnt/mergerfs/:/data'
    restart: unless-stopped
    image: linuxserver/nzbget

  plex:
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - '/data/plex:/config'
      - '/mnt/mergerfs/media:/media'
      - '/data/transcode:/transcode'
    restart: unless-stopped
    image: plexinc/pms-docker:plexpass

  jellyfin:
    container_name: jellyfin
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - '/data/jellyfin:/config'
      - '/data/.cache/jellyfin:/cache'
      - '/mnt/mergerfs/media:/media'
      - '/data/transcode:/transcode'
    ports:
      - 8095:8096
      - 8925:8920
    restart: unless-stopped
    image: jellyfin/jellyfin

  emby:
    container_name: emby
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    volumes:
      - '/data/emby:/config'
      - '/mnt/mergerfs/media:/media'
      - '/data/transcode:/transcode'
    ports:
      - 8096:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    image: linuxserver/emby:beta
```
