### ISSUE TITLE
Fail to change library setting

### ISSUE THREAD

**Issue by jahmad** [jellyfin/jellyfin#2560]
**Describe the bug**
Trying to change library settings, only results loading symbol forever, no changes happen.

**System (please complete the following information):**
 - OS: Debian
 - Virtualization: Docker (linuxserver image)
 - Clients: macOS
 - Browser: Chrome 80
 - Jellyfin Version: 10.5.0

**To Reproduce**

1. Go to Dashboard -> Library
2. Pick a library
3. Click on three dots
4. Select manage library
5. Change some setting, Click OK
6. Loading symbol keep spinning, no changes happened on settings.

**Expected behavior**
Setting changes

**Logs**
Browser console game me this error:

```
 Uncaught Error: null name
    at ApiClient.updateVirtualFolderOptions (apiclientcore.js?v=10.5.0:883)
    at HTMLButtonElement.onEditLibrary (medialibraryeditor.js?v=10.5.0:14)
ApiClient.updateVirtualFolderOptions @ apiclientcore.js?v=10.5.0:883
onEditLibrary @ medialibraryeditor.js?v=10.5.0:14
```

**Comment by Artiume** [comment]
Were you trying to rename the library?

**Comment by jahmad** [comment]
Nope, I was trying to disable inotify.  I've tried it a few times, even doing nothing and go straight to clicking OK. results is the same.

**Comment by jahmad** [comment]
OK, found the culprit, my own mistake.

So i changed installation from official image to linuxserver image (playing out with /dev/dri permissions), and moved folders around due to different directory layout.

this issue came from different root path on metadata record (/config/root) with actual path (/config/data/root). trying symlink to fix it doesn't help.

so, new question: where is this record located? is there a quicker way to change this instead of rebuilding the whole library?

last, feel free to close this issue, consider my request has changed to "please make a clearer error message."

thank you.

**Comment by Artiume** [comment]
One of the things I want to fix is the disparity between our image and the linuxserver image. I'd like to be able to freely switch between images.

If you want to use HWA with our image, you can but you need to drop your compose to v2 and use user: 1000:1000 and group_add: 44 (or whatever group is video uses)

**Comment by jahmad** [comment]
Ah! so there is group_add on older compose file version.. thank you for the hint.

**Comment by jahmad** [comment]
decoding works but not encoding.

card0 and renderD128 owned by different group,  video(44) and render(107). I think there is a need for both group existed inside the container for add_group to works.

I'll go back to linuxserver image for now and deal with consequence of moving folder around.

**Comment by Artiume** [comment]
Hm, what if you add the render to the video group on the host?

**Comment by jahmad** [comment]
I've added both gids to group_add, but since there is no group with gid 107 inside the container, there is no effect.

I believe linuxserver workaround this problem by [adding new group](https://github.com/linuxserver/docker-jellyfin/blob/master/root/etc/cont-init.d/40-gid-video) in their startup.

as for changing device permission directly, I don't think I want to mess around with udev rules, don't have enough knowledge on it.

**Comment by Artiume** [comment]
Can I see your compose?

I was thinking about it. Instead of manually moving all on your files, you could mount each folder explicitly. This'll dirty up the compose a bit but it'd be an easy template to convert between the two images.

**Comment by jahmad** [comment]
official image:
```
version: "2"

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    network_mode: host
    logging:
      options:
        tag: jellyfin
    user: 120:120
    group_add:
    - 44
    - 107
    devices:
    - /dev/dri:/dev/dri
    volumes:
    - /srv/jellyfin:/config:rw
    - /data/media:/data/media:ro
    restart: unless-stopped
```

linuxserver image
```
version: "3"

services:
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    network_mode: host
    logging:
      options:
        tag: jellyfin
    environment:
    - PUID=120
    - PGID=120
    - TZ=Asia/Jakarta
    - UMASK_SET=022
    devices:
    - /dev/dri:/dev/dri
    volumes:
    - /srv/jellyfin:/config:rw
    - /data/media:/data/media:ro
    restart: unless-stopped
```
