### ISSUE TITLE
Cannot initialize password resets from out of network

### ISSUE THREAD

**Issue by linetrimmer** [jellyfin/jellyfin#2869]
**Describe the bug**
Password resets can only be initialized from inside the local network, but in almost every case where a password will need to be reset, the person initializing it is someone I have shared the server with (i.e., they are outside the local network). With [jellyfin-accounts](https://github.com/hrfee/jellyfin-accounts), managing passwords for users is much simpler, and users can carry out the password reset process completely on their own through email. Or at least they could, if password resets could be initialized anywhere but the server's location. 

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Safari
 - Jellyfin Version: 10.5.4, linuxserver
 - Reverse Proxy: nginx

**To Reproduce**
1. Visit the server from an external address
2. Attempt to reset a password

**Expected behavior**
The actual password reset process

**Comment by aleksasiriski** [comment]
This needs to get addressed. Even if you setup something like this using request headers it still doesn't work (even added the proxy to the Networking settings):

```
jellyfin:
    image: jellyfin/jellyfin:latest
    environment:
      - TZ=Europe/Berlin
      - JELLYFIN_PublishedServerUrl=https://jellyfin.$ROOT_DOMAIN
    volumes:
      - jellyfin-conf:/config:Z
      - jellyfin-cache:/cache:Z
    restart: always
    labels:
      - "traefik.http.middlewares.forgot-password-forwarded.headers.customrequestheaders.X-Forwarded-For=127.0.0.1"
      - "traefik.http.middlewares.forgot-password-real.headers.customrequestheaders.X-Real-Ip=127.0.0.1"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.$ROOT_DOMAIN`)"
      - "traefik.http.routers.jellyfin-forgot-password.rule=Host(`jellyfin.$ROOT_DOMAIN`) && (Path(`/Users/ForgotPassword`) || Path(`/Users/ForgotPassword/Pin`))"
      - "traefik.http.routers.jellyfin-forgot-password.middlewares=forgot-password-forwarded@docker,forgot-password-real@docker"
```
