### ISSUE TITLE
Jellyfin Will Not Start After Copying Over Appdata Folder

### ISSUE THREAD

**Issue by Alcatraz077** [jellyfin/jellyfin#3111]
**Describe the bug**
Jellyfin will not start after copying over appdata folder.

**System (please complete the following information):**
 - OS: Debian 10.4
 - Virtualization: Docker
 - Clients: N/A
 - Browser: N/A
 - Jellyfin Version: 10.5.5
 - Playback: N/A
 - Installed Plugins: AudioDB (default), MusicBrainz (default), Anime, IPTV, Trakt (manual) 
 - Reverse Proxy: None
 - Base URL: None
 - Networking: Host
 - Storage: Local

**To Reproduce**

1. Installed Jellfyin, went through initial setup.

2. Installed IPTV plugin. Restarted, no error.

3. Installed Anime plugin. Restarted, no error.

4. Installed Trakt plugin. Restarted, no error. 

5. Stopped Jellyfin, copied and replaced files over from original appdata folder to new Jellyfin install. 

6. Chown -R'd all files within jellyfin to align with user permissions.

7. Started Jellyfin, error occurs.

**Expected behavior**
Jellyfin to start with database/users restored.

**Logs**
```
[09:32:55] [INF] [1] Main: Jellyfin version: 10.5.5
[09:32:55] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll", "--datadir", "/config", "--cachedir", "/cache", "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[09:32:55] [INF] [1] Main: Operating system: Linux
[09:32:55] [INF] [1] Main: Architecture: X64
[09:32:55] [INF] [1] Main: 64-Bit Process: True
[09:32:55] [INF] [1] Main: User Interactive: True
[09:32:55] [INF] [1] Main: Processor count: 8
[09:32:55] [INF] [1] Main: Program data path: /config
[09:32:55] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
[09:32:55] [INF] [1] Main: Application directory: /jellyfin/
[09:32:55] [INF] [1] ServerConfigurationManager: Setting cache path: /tmp
[09:32:55] [INF] [1] App: Loading assemblies
[09:32:55] [FTL] [1] Main: Error while starting server.
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
   at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
   at Emby.Server.Implementations.ApplicationHost.InitAsync(IServiceCollection serviceCollection)
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[09:32:55] [INF] [1] App: Disposing CoreAppHost
[09:32:55] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

**Additional context**
I tried just installing Jellyfin, then copying appdata over originally, and that's where this began. After discussion on Riot it was decided for me to install each plugin individually.

**Comment by Alcatraz077** [comment]
My docker compose file (with relevant Jellyfin section).

```yaml
###JELLYFIN###  
  jellyfin:
    container_name: jellyfin
    volumes:
      - /mnt/storage/media/4kmovies:/4kmovies
      - /mnt/appdata/jellyfin/:/config
      - /mnt/storage/media/tv/:/tv
      - /mnt/storage/media/music/:/music
      - /mnt/appdata/jellyfin/cache/:/cache
      - /mnt/storage/media/anime:/anime
      - /tmp/jellyfin/:/tmp
      - /mnt/storage/media/other:/other
      - /mnt/storage/media/movies/:/movies
#    networks:
#      - public
    network_mode: host
    restart: unless-stopped
    ports:
      - '8086:8096/tcp'
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    image: jellyfin/jellyfin
```

Upon further discussion with @Artiume , I was advised jellyfin/jellyfin doesn't support PUID/PGID, but instead uses `user: 1000:1000` notation in the docker compose file. 

Adjusted so now my compose file reads (in part):

```yaml
###JELLYFIN###  
  jellyfin:
    container_name: jellyfin
    user: 1001:1001
    volumes:
      - /mnt/storage/media/4kmovies:/4kmovies
      - /mnt/appdata/jellyfin/:/config
      - /mnt/storage/media/tv/:/tv
      - /mnt/storage/media/music/:/music
      - /mnt/appdata/jellyfin/cache/:/cache
      - /mnt/storage/media/anime:/anime
      - /tmp/jellyfin/:/tmp
      - /mnt/storage/media/other:/other
      - /mnt/storage/media/movies/:/movies
#    networks:
#      - public
    network_mode: host
    restart: unless-stopped
    ports:
      - '8086:8096/tcp'
    environment:
      - TZ=America/Chicago
    image: jellyfin/jellyfin
```

**Comment by Alcatraz077** [comment]
This resulted in Jellyfin not starting, and the logs showing:

```
Failed to create CoreCLR, HRESULT: 0x80004005
```

Over and over again. Per @JustAMan , I added the `COREHOST_TRACE=1` as an environmental variable. 

Logs: 
[jellyfin_log.txt](https://github.com/jellyfin/jellyfin/files/4629582/jellyfin_log.txt)

**Comment by Alcatraz077** [comment]
I was able to pull the full logs directly out of the docker container. The log file was too large for Github, so I've zipped it.

[jellyfin.zip](https://github.com/jellyfin/jellyfin/files/4630467/jellyfin.zip)

**Comment by JustAMan** [comment]
Nothing stands out in these logs for me... someone else would have to take a look I think. paging @jellyfin/backend

**Comment by mark-monteiro** [comment]
@Alcatraz077 Can you clarify exactly what files you copied over? What folder are you referring to by "original appdata folder"? Can you let us know exactly what files/folders you copied over?

**Comment by Alcatraz077** [comment]
@mark-monteiro All the files normally in the config for Jellyfin. In docker, appdata just refers to whatever path you're mounting the config folder of the application to. I copied everything from a backup I created just before the migration. The exact command I used was `rsync -avPz /mnt/ext/jellyfin /mnt/appdata/jellyfin` per artiume's request. The exact files and directories copied are attached.

[jellyfin_files.zip](https://github.com/jellyfin/jellyfin/files/4638728/jellyfin_files.zip)

**Comment by mark-monteiro** [comment]
It looks like you copied over the plugins from your old install and overwrote the ones in your new install. They are in the `plugins` folder. I think you shouldn't copy that folder

**Comment by Alcatraz077** [comment]
I stopped my Jellyfin docker, wiped the folder, and copied over everything (but the plugin folder) to the Jellyfin folder. Stared the container back up, same messages as before.

**Comment by mark-monteiro** [comment]
Perhaps try copying over the appdata folder before installing any plugins. Remove the existing `plugins` folder, if any, then copy over the files (again, do not copy the plugins folder). Then see if you can start up the server.

The error you are getting appears to be from trying to load a plugin .dll so I think you should try getting the server running without any plugins installed.

**Comment by Alcatraz077** [comment]
Tried this, issue persists, same messages as before. I even tried to clean install Jellyfin (blew away my config folder, and re-created the container), same errors.

**Comment by Alcatraz077** [comment]
I just stopped my container, blew away the container, image, and re-created all of it (with the config folder copied over [excluding the plugin folder]). No dice.

**Comment by Alcatraz077** [comment]
Yeah, no matter what I do, Jellyfin will not run on docker on my server. I got it running on baremetal, but I'd really like it running on docker.

**Comment by Artiume** [comment]
If you're unable to get it working, you could always use this utility to transfer watch status to new accounts

https://github.com/CobayeGunther/Emby2Jelly

**Comment by Alcatraz077** [comment]
Since Jellyfin will not boot up on docker, I can't get the api key for use with that utility (unless it's in a file somewhere?).

**Comment by Artiume** [comment]
As far as i'm aware, your situation is as such, You had a docker running at /locationA, moving it to  /locationB breaks stuff.

Move it back to A so it works again

**Comment by Alcatraz077** [comment]
Perhaps I didn't explain it well enough. I've migrated from Unraid to Debian. Before I shut down Unraid for the last time, I copied over the entire appdata folder for Jellyfin (along with other docker containers I had running). I installed Debian, and docker, and proceeded to reinstall Jellyfin via docker. I then copied the config folder from Jellyfin to the new location, and attempted to start Jellyfin back up. 

Ended up getting the errors I originally described. I've tried wiping the config folder, removing the image, and the container. Tried to reinstall, without moving any old files over. Got the same error. 

I even tried another Jellyfin docker image (by the LinuxServer.io team), after adjusting the variables needed. No dice. 

Installed Jellyfin via apt onto Debian. Runs without issue on clean install, but any files I move over from the old (original) config folder, it breaks. 

Hence my deceleration of it will work on bare metal, but not docker.

**Comment by Artiume** [comment]
Did you try the linuxserver/jellyfin or jellyfin/jellyfin image? IIRC, Unraid uses the linuxserver image which isnt compatible with our image.

**Comment by Alcatraz077** [comment]
On Unraid I was using linuxserver/jellyfin, until one day it broke spectacularly with the same hex error message I'm getting now. I ended up moving to jellyfin/jellyfin on Unraid, which worked without issue.

**Comment by Alcatraz077** [comment]
I removed the /tmp mapping, and pre-made the directory with the appropriate ownership. Jellyfin will now start.

**Comment by pciavald** [comment]
Hey there, i'm experiencing the same error although my docker-compose does not map /tmp.

```
jellyfin    | [12:15:36] [INF] [1] Main: Jellyfin version: 10.6.4
jellyfin    | [12:15:36] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_MEDIA_DIR, /media]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]", "[JELLYFIN_DATA_DIR, /config]"]
jellyfin    | [12:15:36] [INF] [1] Main: Arguments: ["/jellyfin/jellyfin.dll"]
jellyfin    | [12:15:36] [INF] [1] Main: Operating system: Linux
jellyfin    | [12:15:36] [INF] [1] Main: Architecture: X64
jellyfin    | [12:15:36] [INF] [1] Main: 64-Bit Process: True
jellyfin    | [12:15:36] [INF] [1] Main: User Interactive: True
jellyfin    | [12:15:36] [INF] [1] Main: Processor count: 24
jellyfin    | [12:15:36] [INF] [1] Main: Program data path: /config
jellyfin    | [12:15:36] [INF] [1] Main: Web resources path: /jellyfin/jellyfin-web
jellyfin    | [12:15:36] [INF] [1] Main: Application directory: /jellyfin/
jellyfin    | [12:15:36] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
jellyfin    | [12:15:36] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
jellyfin    | [12:15:36] [FTL] [1] Main: Error while starting server.
jellyfin    | System.BadImageFormatException: Bad IL format.
jellyfin    |    at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
jellyfin    |    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
jellyfin    |    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.GetComposablePartAssemblies()+MoveNext()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.GetTypes(IEnumerable`1 assemblies)+MoveNext()
jellyfin    |    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
jellyfin    |    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
jellyfin    |    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.DiscoverTypes()
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.Init(IServiceCollection serviceCollection)
jellyfin    |    at Jellyfin.Server.Program.StartApp(StartupOptions options)
jellyfin    | [12:15:36] [INF] [1] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
jellyfin    | [12:15:36] [INF] [2] Main: Received a SIGTERM signal, shutting down
```

```
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    volumes:
      - /data/audiovisuel/music/jellyfin/config:/config
      - /data/audiovisuel/music/jellyfin/music:/media
    expose:
      - 8096
```

It worked for months until it failed, I did not make any configuration changes before it failed. I'm guessing some kind of file got corrupted and now this error is thrown, from web search seems to be a dotnet error. I guess from a user point of view, more info about the corrupted file and reason of the error would be beneficial to show in the logs ?

I'm investigating, will update.
