### ISSUE TITLE
TVDB API Failure

### ISSUE THREAD

**Issue by just-an-alt** [jellyfin/jellyfin#3201]
**Describe the bug**
After a completely fresh install with default values, Jellyfin fails to download series artwork, as seen in the screenshots. Surprisingly, images of actors, episode titles and show descriptions get downloaded properly

**System (please complete the following information):**
 - OS: Armbian Buster, Rockchip RK3399 CPU
 - Virtualization: Docker
 - Clients: Firefox
 - Browser: Firefox 76.0.1 64-bit
 - Jellyfin Version: 10.5.5
 - Playback: Direct Play
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Bridge
 - Storage: local

**To Reproduce**
1. Install linuxserver.io's jellyfin docker image
2. Set up Jellyfin using the default values, adding the directory containing TV Shows in the process
3. Wait for Jellyfin to complete the directory scan
4. Be dissapointed at the lack of artwork

**Expected behavior**
Beautiful cover art and artwork

**Logs**
Log containing the error: https://paste.debian.net/hidden/658dd188/
Full log: https://files.catbox.moe/d8bkpw.txt

**Screenshots**
![Series overview](https://i.imgur.com/ED1AglC.png)
![Game of Thrones](https://i.imgur.com/n5Ico5t.png)

**Additional context**
My docker-compose config:
```
jellyfin:
        ports:
            - 8096:8096
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - UMASK_SET=022
        volumes:
            - '/home/user/jellyfin:/config'
            - '/bigdata0/media/library/tv:/media/library/tv'
        restart: unless-stopped
        image: linuxserver/jellyfin
```
