### ISSUE TITLE
How can I 100% disable media deletion?

### ISSUE THREAD

**Issue by renannprado** [jellyfin/jellyfin#3517]
Sorry I don't have time now to properly describe, I'll later describe it better but basically Jellyfin is deleting media out of the blue.

It happened even though I have the `Allow Media Deletion From` unset.

Other people seems to have the same problem and it's a huge blocker IMO.

![image](https://user-images.githubusercontent.com/2359543/86591700-588d3100-bf92-11ea-9981-5e2d68bfe6cc.png)

also related: https://www.reddit.com/r/jellyfin/comments/f6hwsr/jellyfin_deleting_files/

**Comment by dkanada** [comment]
The easiest way is to only give Jellyfin read access to your data, which is the one thing we suggest more than anything else. In any case though, we'll look into the issue.

**Comment by renannprado** [comment]
@dkanada I've tried to do so 'cause actually this is the second time that his happens.

And I've set the `readOnly: true` flag in kubernetes... still doesn't work and I suspect it's because of https://github.com/docker/for-linux/issues/788 .
Now I'm giving it third try, but I don't think it will work since there seems to be a limitation in docker.

Relates to https://github.com/jellyfin/jellyfin-docs/issues/124 as well.

this is the deployment file I have

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-deployment
  namespace: home
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      name: jellyfin-deployment
  template:
    metadata:
      name: jellyfin-deployment
      labels:
        name: jellyfin-deployment
    spec:
      containers:
      - image: linuxserver/jellyfin:v10.5.5-ls59
        name: jellyfin
        resources:
          requests:
            cpu: "50m"
            memory: "64M"
          limits:
            cpu: "2"
            memory: 4Gi
        ports:
        - containerPort: 8096
        env:
        - name: TZ
          value: Europe/Berlin
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        volumeMounts:
        - name:  jellyfin-data
          mountPath: /config
        - name:  torrent-data
          mountPath: /torrent-data
          readOnly: true
      volumes:
        - name: jellyfin-data
          persistentVolumeClaim: 
            claimName: jellyfin-data-pvc
        - name: torrent-data
          persistentVolumeClaim: 
            claimName: torrent-data-pvc
            readOnly: true
```
