### ISSUE TITLE
Change Color of Switch Track

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin#475]
This may tie in to the theme/colour work that @sparky8251 is doing.

Essentially, right now with the new dark theme, the track for toggle switches is set to black (or nearly black). As a result, a switch just looks like a floating button.

I couldn't tell you where `emby-toggle.css` is being generated, but wherever it is, it ends up with this:
```css
.mdl-switch__track {
    background: rgba(0, 0, 0, .2);
    height: 1em;
    -webkit-border-radius: 1em;
    border-radius: 1em;
    cursor: pointer
}
```

That background should be changed to something lighter.
