### ISSUE TITLE
Unable to Add SMB Server - Works fine in Emby

### ISSUE THREAD

**Issue by FreeSoftwareServers** [jellyfin/jellyfin#5456]
I just setup Emby today then found Jellyfin. I got Jellyfin setup now too (both via docker-compose) and I am unable to add my SMB Shares. Notes:

* They work fine in Emby
* The SMB Share is unrestricted access to entire LAN without Authentication

I'm not sure what information to share to help debug, but I'm happy to provide more/logs etc. At this time, I will be staying w/ Emby likely, but can't wait to migrate over to Jellyfin asap.

**Comment by cvium** [comment]
By "Add SMB server", do you mean mounting it on the local filesystem and adding _that_ path to Jellyfin? Or do you mean adding something like `smb://1.2.3.4/` to Jellyfin?

The former works, the latter hasn't existed since _early_ 2019.

**Comment by PrplHaz4** [comment]
Since you're using docker, it's fairly easy to create a CIFS volume in docker-compose.  I wouldn't count on SMB native support anytime soon.

```
volumes:
  movies:
    driver: local
    driver_opts:
      type: cifs
      o: vers=3.02,mfsymlinks,username=SMBUSERNAME,password=SMBPASSWORD
      device: "//192.168.1.11/Video/Movies"
```
