### ISSUE TITLE
Cannot customize location of Live TV recordings

### ISSUE THREAD

**Issue by yobyot** [jellyfin/jellyfin#5910]
Using the container version of Jellyfin, I would like to have Live TV recordings (supplied by a Silicon Dust tuner) stored on an external SMB share.

Using Docker Compose to create a container, this is not possible because the default path to recordings is `/config/data/livetv/recordings`. This path can be altered via a change to `JELLYFIN_CONFIG_DIR`. But placing any part of the directory specified by `JELLYFIN_CONFIG_DIR` on an external SMB share causes Jellyfin to fail to initialize in the container.

Here's my sample docker-compose.yml. Uncommenting any of the commented specs will cause a new Jellyfin container to fail.

```
version: "3"
services:
  jellyfin:
    container_name: "jellyfin"
    image: jellyfin/jellyfin
    user: 1000:998
    network_mode: "host"
    restart: "unless-stopped"
    environment:
    #  - JELLYFIN_LOG_DIR=/config/log
    #  - JELLYFIN_CONFIG_DIR=/config/config
    #  - JELLYFIN_DATA_DIR=/config
     - JELLYFIN_MEDIA_DIR=/media
     - JELLYFIN_CACHE_DIR=/cache
    volumes:
    #  - /smbexternalshare/config/log:/config/log:rw
    #  - /smbexternalshare/config/config:/config/config:rw
    # - /smbexternalshare/config:/config:rw
      - /smbexternalshare:/media:rw
      - /smbexternalshare/cache:/cache:rw
    #  - /smbexternalshare:/config/data/livetv/recordings:rw
```
