### ISSUE TITLE
websocket doesn't work

### ISSUE THREAD

**Issue by NunzioArdi** [jellyfin/jellyfin#6153]
**Describe the bug**
I have error on my jellyfin websocket and i can't use syncplay.  Can't seem to find where the problem could be.
The problem is not there when I connect with a local ip 192.168.x.x 
Thank you (sorry for the english) 

**System (please complete the following information):**
 - OS: Ubuntu
 - Virtualization: Docker
 - Clients: Browser
 - Browser: All
 - Jellyfin Version: 10.7.5
 - Playback: - 
 - Installed Plugins: new install
 - Reverse Proxy: nginx
 - Base URL: yes: jellyfin.<domain name>
 - Networking: [e.g. Host, Bridge/NAT]
 - Storage: local

Client -> DNS host -> server -> docker(nginx revers proxy) -> docker(jellyfin)

**Screenshots**
![tmp_jelly_brower_error_websocket](https://user-images.githubusercontent.com/15235621/120903820-aac64e80-c648-11eb-9e81-4b01e17b5ec5.png)

**Additional context**
jellyfin.conf (nginx)

```nginx
server {
        listen 80;
        listen [::]:80;
        server_name jel<doamine name>;   # Domain name

        # Headers http
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";

        set $jellyfin 172.17.0.1;

    location / {
        # Proxy main Jellyfin traffic
        proxy_pass http://$jellyfin:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
    }

    # location block for /web - This is purely for aesthetics so /web/#!/ works instead of having to go to /web/index.html/#!/
    location = /web/ {
        # Proxy main Jellyfin traffic
        proxy_pass http://$jellyfin:8096/web/index.html;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location /socket {
        # Proxy Jellyfin Websockets traffic
        proxy_pass http://$jellyfin:8096;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

}
```
docker-compose.yml (nginx)
```yml
version: "2.4"
services:
        nginx:
                image: nginx:latest
                container_name: nginx
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf:ro
                        - ./sites-enabled:/etc/nginx/sites-enabled:ro
                        - ./ssl:/etc/nginx/ssl:ro
                        - ./logs:/var/log/nginx
                        - ./websites:/srv:ro
                ports:
                        - 443:443
                        - 80:80
                restart: unless-stopped
```

docker-compose.yml (jellyfin)
```yml
version: "3.7"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Paris
            - UMASK_SET=022 #optional
    volumes:
            - ./config:/config
            - <media1>
            - <media2>
    ports:
            - 8096:8096 # http
            - 1900:1900/udp # DNLA
            - 7359:7359 # Jellyfin auto-discovery
    restart: unless-stopped
```
