### ISSUE TITLE
Jellyfin overriding sort title metadata changes

### ISSUE THREAD

**Issue by ryanwalder** [jellyfin/jellyfin#6277]
**Describe the bug**

I am running the [linuxserver/jellyfin](https://docs.linuxserver.io/images/docker-jellyfin) container with `/config` mapped to a folder on the host. This works, it saves all configs as expected and survive a stop/start of the container.

Having gone through and manually fixed the `Sort Title` for all the movies that needed fixing about a month ago I have just noticed they have since reverted.

I have a feeling it could be a metadata agent overwriting the `Sort Title` field due to it surviving a restart of the container/host but overwriting it sometime over the last month.

I did notice that the `Sort Title` now gets filled with text by default when scanning a library for the first time where it didn't in previous versions (not sure the exact release this changed). Not sure if that might be related.

**System (please complete the following information):**
 - Host OS: Ubuntu 20.04
 - Virtualization: Docker ([linuxserver/jellyfin](https://docs.linuxserver.io/images/docker-jellyfin))
 - Clients: Kodi/Web
 - Browser: Firefox 89.0.2 (Linux)
 - Jellyfin Version: 10.7.6

**Docker Compose:**
```
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/linuxserver/jellyfin:latest
    ports:
      - "8096:8096"
      - "7359:7359/udp"
    environment:
      - PUID=1000
      - PGID=502
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /srv/zfs/docker/jellyfin:/config
      - /srv/zfs/rust/ftp:/media/ftp:ro
    restart: unless-stopped
```

**To Reproduce**

1. Update `Sort Title` of movie
2. Wait some amount of time (at most, a month)
3. Sort title is gone

**Expected behavior**
1. Update `Sort Title`
2. It does not change

**Metadata Settings for Library**

![image](https://user-images.githubusercontent.com/10901150/125101570-43ca0880-e0d2-11eb-9549-65dcf5ed4c61.png)
