### ISSUE TITLE
Album Artwork creating collages for no apparent reason.

### ISSUE THREAD

**Issue by Trevo525** [jellyfin/jellyfin#6741]
**Describe the bug**
Random albums in my music library are creating collages of the cover. I found two reddit ( [one](https://www.reddit.com/r/jellyfin/comments/civlgo/4_covers_in_one_for_music_albums/) and [two](https://www.reddit.com/r/jellyfin/comments/fx6849/music_album_covers_doing_some_really_weird_stuff/) ) posts where users had the same issue but there was never a solution. I created [my own](https://www.reddit.com/r/jellyfin/comments/q4c3ox/jellyfin_music_album_creating_image_collage/) but obviously, this is a better place for this.

**System (please complete the following information):**
 - OS: Ubuntu 21.04 (GNU/Linux 5.11.0-38-generic x86_64)
 - Virtualization: Docker-Compose ([LinuxServer](https://docs.linuxserver.io/images/docker-jellyfin) image)
 - Clients: Server-side. But, I can see the same thing on browser, Android apps, and Finamp app.
 - Jellyfin Version: 10.7.7
 - Installed Plugins: AniDB, AudioDB, Bookshelf, Cover Art Archive, merge Versions, Musicbrainz, OMDb, Playback Recording, Reports, Skin Manager, TheTVDB, Theme Songs.
 - Reverse Proxy: caddyV2
 - Base URL: none
 - Networking: Default Docker-Compose network configuration
 - Storage: local for DB and config. NFS for media

```
---
version: "3.5"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=jellyfin.mydomain.com #optional
    volumes:
      - /home/owner/docker/jellyfin/config:/config
      - /mnt/nfs:/data/library/
      - /mnt/nvmessd/transcodes:/transcodes
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped
```

**To Reproduce**
Seemingly completely random. I only noticed a few weeks after I had installed and been using the software. I can get it to do the "collage" again if I click "Refresh Metadata" on the albums that have this issue. However, if I do that same thing on Albums that do not already have some sort of collage done to them it doesn't do it to them.

**Expected behavior**
I thought that it had just scrapped the album art and the database it pulled from had weird images. So, the expected behavior was to refresh the images.

**Server Logs**
```
[2021-10-08 21:48:40.498 -04:00] [INF] [136] Emby.Drawing.ImageProcessor: Creating image collage and saving to "/config/cache/temp/d89715c5de2749a7b10ee19a259cfcd8.png"
[2021-10-08 21:48:40.576 -04:00] [INF] [136] Emby.Drawing.ImageProcessor: Completed creation of image collage and saved to "/config/cache/temp/d89715c5de2749a7b10ee19a259cfcd8.png"
```

**Screenshots**
![image](https://i.imgur.com/OQBDmHb.jpg)

![image](https://i.imgur.com/RbipjPH.png)

![image](https://i.imgur.com/9WTecez.png)

![image](https://i.imgur.com/ciSsI0c.png)

**Additional context**
The log that I attached makes it obvious that it is using `Emby.Drawing.ImageProcessor`. After a google of that, I found that there is a [CreateImageCollage](https://jellyfin.org/docs/plugin-api/Emby.Drawing.ImageProcessor.html#Emby_Drawing_ImageProcessor_CreateImageCollage_MediaBrowser_Controller_Drawing_ImageCollageOptions_System_String_) method in [Emby.Drawing.ImageProcessor](https://jellyfin.org/docs/plugin-api/Emby.Drawing.ImageProcessor.html).

I don't know what is calling that method. All that I know is that I can replicate it by running "Refresh Metadata" on the album again. I realized when making this post that I had two plugins that specifically have to do with music. So, I'll try disabling them and see if that fixes my issue. But, I will make this post anyways so that future people can see it. OR if it doesn't work to see if I can still get a solution.
