### ISSUE TITLE
[Issue]: New installation doesn't open wizard

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin#7001]
### Please describe your bug

A new installation via docker of Jellyfin 10.7.7.

We're unable to connect to the selected server right now. Please ensure it is running and try again.

Upon visiting http://192.168.x.x:8096/ there is only the option to 'Select Server' and upon clicking the server name, the message is "We're unable to connect to the selected server right now. Please ensure it is running and try again."

It seems unable to access the setup wizard.  There is nothing strange in the logs.

```
 jellyfin:
    image: jellyfin/jellyfin
    container_name: "jellyfin"
    user: 1001:1001
    group_add:
      - 107 #render
      - 44  #video
    #network_mode: "host"
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /media/pool:/media/pool
    environment:
      - TZ=America/NewYork
    restart: unless-stopped
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    ports:
      - 8096:8096
```

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS: Debian 11
- Virtualization: Docker
- Clients: Chrome
- Browser: Chrome
- FFmpeg Version: docker
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: N/A
- Reverse Proxy: N/A
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
