### ISSUE TITLE
[Issue]: group_add doesn't support integer in Compose v2

### ISSUE THREAD

**Issue by SyRaza** [jellyfin/jellyfin#7676]
### Please describe your bug

I reinstalled my server yesterday from scratch and of course installed docker and docker compose as per the website. Docker Compose v1.2.9 was still the primary install version yesterday, with the option to install  Docker Compose 2.4.1. 

As of today, Docker Compose 1.2.9 is deprecated and the primary installation on docker's website is Docker Compose 2.4.1.

I decided to upgrade my Docker Compose version. My docker compose yaml file worked perfectly on 1.2.9 but wouldn't run on 2.4.1. 

The error I got was `'group_add[0]' expected type 'string', got unconvertible type 'int', value: '109''group_add[0]' expected type 'string', got unconvertible type 'int', value: '109'`

My Jellyfin compose configuration is the only one using `group_add`. After disabling the Jellyfin compose configuration in my yaml file, my file worked perfectly in compose 2.4.1

Here is my jellyfin compose configuration. 

```
# Jellyfin - Software Media System 
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - lsio
    group_add:
      - 109
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - $USERDIR/docker/jellyfin:/config
      - /mnt/storage/media:/media
      - /mnt/storage/cache:/cache
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JELLYFIN_PublishedServerUrl=[redacted]
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
    - /dev/dri:/dev/dri
    - /dev/nvidia0:/dev/nvidia0
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
```

For the time being, I've rolled back to Compose v1.2.9 until there is a fix for this.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Ubuntu server 22.04
- Virtualization:
- Clients:Browser,
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:SWAG
- Base URL:
- Networking:
- Storage:lcal
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
