### ISSUE TITLE
[Issue]: 10.8.3-armhf on Docker won't start

### ISSUE THREAD

**Issue by ortizdaniel** [jellyfin/jellyfin#8208]
### Please describe your bug

Hello!

I'd like to start saying sorry because I have literally no information whatsoever about the error. There are no logs anywhere.

Basically, Jellyfin won't start on my Raspberry Pi 4 using Docker. Any version after 10.7.7 won't start actually. The containers start and instantly die exiting with code 132. Sadly, that's as much information as I have right now.

This is what my `docker-compose` file looks like, if relevant:

```
version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.3-armhf
    container_name: jellyfin
    #user: daniel:1000
    network_mode: "host"
    volumes:
      - /opt:/opt
      - /home/daniel/jellyfin/config:/config
      - /home/daniel/jellyfin/cache:/cache
      - /home/daniel/jellyfin/media:/media
    #  - /home/daniel/jellyfin/media2:/media2:ro
    restart: "always"
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '2'
    #      memory: 1024M
    # Optional - alternative address used for autodiscovery
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/video13:/dev/video13
      - /dev/video14:/dev/video14
      - /dev/video15:/dev/video15
      - /dev/video16:/dev/video16
      - /dev/video18:/dev/video18
```

I have tried commenting other parts of it to no avail (such as the `devices` or `volumes`).

### Jellyfin Version

10.8.0

### if other:

10.8.x-armhf

### Environment

```markdown
- OS: Raspbian 5 32 bits
- Virtualization: Docker 
- Clients: (attempting) Browser
- Browser: none (since it won't start)
- FFmpeg Version: whichever comes with the Docker image
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: none
- Reverse Proxy: none
- Base URL: none
- Networking: host
- Storage: local
```

### Jellyfin logs

```shell
Attaching to jellyfin
jellyfin exited with code 132
```

### Please attach any screenshots here

![Captura de pantalla 2022-08-04 a las 23 10 14](https://user-images.githubusercontent.com/5923590/182953241-06e67f4a-0e18-4944-a8a0-c586b4cd6b81.png)

![Captura de pantalla 2022-08-04 a las 23 10 44](https://user-images.githubusercontent.com/5923590/182953304-eef5d1b6-021c-4492-9e3a-bc547da4a39f.png)

![Captura de pantalla 2022-08-04 a las 23 12 06](https://user-images.githubusercontent.com/5923590/182953508-7f4c8199-e247-4d13-a858-c18aa39085a4.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
