### ISSUE TITLE
Reverse Proxy Connection Issues

### ISSUE THREAD

**Issue by amingle4** [jellyfin/jellyfin#8330]
### Please describe your bug

This issue is also posted in the [jellyfin-android issues ](https://github.com/jellyfin/jellyfin-android/issues/742)section, but since it seems to be more generic than just Android, I am posting it here as well.

### Describe the bug

I am using Jellyfin via Docker behind a reverse proxy (was originally NGINX; is now traefix v2). For testing purposes, I also mapped a port to the host for http connection.

There are a couple issues:

If I go to http://SERVERIP:8096/system/info/public => it loads very quickly and returns:
`{"LocalAddress":"http://172.18.0.9:8096","ServerName":"jellyfin","Version":"10.8.4","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"3884546a3c324cd88ad1730c943afafe","StartupWizardCompleted":true}`

If I go to https://jellyfin.MYDOMAIN.com/system/info/public => it takes about 5 seconds to load and returns:
`{"LocalAddress":"https://172.18.0.9:8920","ServerName":"jellyfin","Version":"10.8.4","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"3884546a3c324cd88ad1730c943afafe","StartupWizardCompleted":true}`

I also can't access the server via the Android app. I _can_ access it through the web browser on my Android device at https://jellyfin.MYDOMAIN.com

No SSL settings are set up on the Jellyfin server - the reverse proxy should be handling all the SSL with the client, then communicating with Jellyfin via HTTP only.

I have the full certificate loaded into my reverse proxy, so I do not have reason to believe that is the cause of the issue.

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Windows / Android
- Virtualization: Docker
- Clients: Browser, Android
- Browser: Chrome 104
- Reverse Proxy: NGINX and traefix v2
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by crobibero** [comment]
Please post your nginx config.

**Comment by amingle4** [comment]
Here's what I tried for both NGINX and traefik:

**NGINX Config**

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name jellyfin.MYDOMAIN.com;

    resolver 127.0.0.11 valid=30s;
	
    ssl_certificate /certs/fullchain.pem;
    ssl_certificate_key /certs/privkey.pem;

    location / {
        proxy_connect_timeout 60;
        proxy_read_timeout 60;
        proxy_send_timeout 60;
        proxy_intercept_errors off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP            $remote_addr;
        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto            $scheme;

	set $jellyfin http://jellyfin:8096;
        proxy_pass $jellyfin;
    }
}

```

**Traefik**

_Static Configuration_
The only part I am including is the entry points:
```
entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https

    websecure:
        address: ":443"
        forwardedHeaders: 
            insecure: true
```

_Dynamic Configuration:_
```
http:
    routers:
        jellyfin_ssl:
            rule: Host(`jellyfin.MYDOMAIN.com`)
            service: "jellyfin_service"
            middlewares: 
                - "jellyfin_headers"
            entryPoints: 
                - "websecure"
            tls: {}
    
    middlewares:
        jellyfin_headers:
            headers:
                customResponseHeaders: 
                    X-Robots-Tag: noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
                stsSeconds: 315360000 
                stsIncludeSubdomains: true
                stsPreload: true
                forceSTSHeader: true
                frameDeny: true
                contentTypeNosniff: true
                browserXssFilter: true
                customFrameOptionsValue: "allow-from https://jellyfin.MYDOMAIN.com"

    services:
        jellyfin_service:
            loadBalancer:
                servers:
                    - url: "http://jellyfin:8096"

```
