### ISSUE TITLE
[Issue]: Unable to Access Internet from Docker (Metadata, Plugins, etc.)

### ISSUE THREAD

**Issue by jboucher614** [jellyfin/jellyfin#8892]
### Please describe your bug

Hi, my Jellyfin instance is currently unable to access the internet to view plugins and load metadata. When I try to go to Plugins > Catalog, I get an endless spinning loading wheel.

The internal Jellyfin logs show a few errors like this one:

`Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing". URL "GET" "/Packages".`

My Jellyfin Docker logs show this:

`Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://[redacted]:8096/jellyfin/Packages?PackageType=UserInstalled to [redacted] in 0:01:40.0075526 with Status Code 500`

I'm running Debian Stable with a Jellyfin Docker container (jellyfin/jellyfin) on the latest image, 10.8.8. The Jellyfin Docker network is "host," and it runs on user 1000 (which is correct for my setup). I recently reconfigured it to be accessed at https://[exampleURL.org]/jellyfin and is accessible via NGINX proxy manager. I also recently enabled UFW on the host machine.

I've tried:

-     disabling my firewall, UFW, and restarting the container
-     accessing the container via both the local IP rather and the HTTPS proxy
-     disabling the /jellyfin custom subdirectory and accessing directly via http://[localIP]:8096, which didn't help

Please let me know if anyone else has had a similar issue or knows of a fix. Thank you!

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:Debian
- Virtualization: Docker
- Clients: Desktop, Browser, and Android
- Browser: Firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins: AudioDB, MusicBrainz, OMDb, StudioImages,TMDb
- Reverse Proxy: NGINX
- Base URL: /jellyfin
- Networking: host, ufw with all 4 jellyfin ports allowed
- Storage: local HDD
```

### Jellyfin logs

```shell
`Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request: "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing". URL "GET" "/Packages".`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EgorBakanov** [comment]
I had same problem with jellyfin and multiple other services on docker. Turns out I misconfigured docker MTU. Check out this articles:
* [How we spent a full day figuring out a MTU issue with docker](https://sylwit.medium.com/how-we-spent-a-full-day-figuring-out-a-mtu-issue-with-docker-4d81fdfe2caf)
* [Docker MTU issues and solutions](https://mlohr.com/docker-mtu/)

**Comment by jboucher614** [comment]
I figured it out. My machine had a problem with connecting to ipv6

**Comment by cclloyd** [comment]
For me, using sysctl to disable ipv6 worked. 

In my instance, this was adding `'--kubelet-arg=allowed-unsafe-sysctls=net.ipv6.*' \ ` to my k3s systemd definition, and in my deployment yaml, I added
```
spec:
  template:
    spec:
      securityContext:
        sysctls:
          - name: net.ipv6.conf.all.disable_ipv6
            value: "1"
          - name: net.ipv6.conf.default.disable_ipv6
            value: "1"
```

**Comment by mrtrandinhvn** [comment]
When I ran the command below, the result confirmed that my docker lacks of a nameserver.
```bash
docker exec -it jellyfin cat /etc/resolv.conf
# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.


# Based on host file: '/etc/resolv.conf'
# Overrides: []
```

The fix for that specific container is adding dns section in my `docker-compose.yml` then restart the container using `docker compose down` and then `docker compose up`
```yml
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    dns:
      - 1.1.1.1
      - 8.8.8.8
```
