### ISSUE TITLE
[Issue]: cannot identify media nor access plugins catalog

### ISSUE THREAD

**Issue by Chr0nos** [jellyfin/jellyfin#9216]
### Please describe your bug

Hi,

When i try to "identify" a media the window keeps loading forever ( the same imply when i try to access the plugins catalog page)

I've also just rm -rf everything then re-setup everything just to be sure that the config/database wasen't in a weird state due to multiples version switching while trying to fix the issue, so everything is from the unstable version of the official container (the same issue occurs in stable)

additionaly when i try to add something in my collection the media is not identified

The issue also affect my ability to add new medias: none of them are recognized by the system 

I'm using the docker-compose setup

```
  jellyfin:
    image: jellyfin/jellyfin:unstable
    network_mode: host
    volumes:
    - /home/user/services/apps/jellyfin/config:/config
    - /home/user/services/apps/jellyfin/cache:/cache
    - /mnt/aiur:/media:ro
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
```

the caddyfile section
```
jellyfin.my-domain.me {
    reverse_proxy 192.168.0.12:8096
    header {
        Content-Security-Policy "manifest-src https://jellyfin.my-domain.me" "connect-src wss://jellyfin.my-domain.me/socket";
    }
}
```

i've also tried to open all the ports on the server (iptables -P INPUT ACCEPT) just to see if it wasen't a firewall issue: same

### Jellyfin Version

Other

### if other:

10.9.0

### Environment

```markdown
- OS: Archlinux
- Virtualization: Docker
- Clients: Browser
- Browser: Brave / Firefox / Chrome
- FFmpeg Version: 5.1.2-Jellyfin
- Hardware Acceleration: none
- Plugins: Intro-Skipper 0.1.7.0
- Reverse Proxy: Caddy
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
services-jellyfin-1  | System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
services-jellyfin-1  |  ---> System.TimeoutException: A task was canceled.
services-jellyfin-1  |  ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
services-jellyfin-1  |    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
services-jellyfin-1  |    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
services-jellyfin-1  |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
services-jellyfin-1  |    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
services-jellyfin-1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
services-jellyfin-1  |    at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
services-jellyfin-1  |    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
services-jellyfin-1  |    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
services-jellyfin-1  |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
services-jellyfin-1  |    --- End of inner exception stack trace ---
services-jellyfin-1  |    --- End of inner exception stack trace ---
services-jellyfin-1  |    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
services-jellyfin-1  |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
services-jellyfin-1  |    at MediaBrowser.Providers.Plugins.Omdb.OmdbItemProvider.GetSearchResultsInternal(ItemLookupInfo searchInfo, Boolean isSearch, CancellationToken cancellationToken)
services-jellyfin-1  |    at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
services-jellyfin-1  |    at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
services-jellyfin-1  | [14:05:14] [INF] [76] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
services-jellyfin-1  | [14:05:14] [INF] [76] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
services-jellyfin-1  | [14:05:14] [INF] [76] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
services-jellyfin-1  | [14:05:14] [INF] [70] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
services-jellyfin-1  | [14:05:14] [INF] [70] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
services-jellyfin-1  | [14:05:14] [INF] [70] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
```

### Please attach any browser or client logs here

node_modules.jellyfin-apiclient.bundle.js?49990ec49236df6df894:1 Sending web socket message: KeepAlive
serviceworker.js:1 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://jellyfin.hidden-domain.me/web/App.tsx","status":404}]
    at y._handleInstall (https://jellyfin.hidden-domain.me/web/serviceworker.js:1:34014)
    at async y._handle (https://jellyfin.hidden-domain.me/web/serviceworker.js:1:33429)
    at async y._getResponse (https://hidden-domain.me/web/serviceworker.js:1:32538)

### Please attach any screenshots here

<img width="798" alt="image" src="https://user-images.githubusercontent.com/889379/215770433-b7ade526-622e-4657-878d-757680740a4a.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chr0nos** [comment]
I've found a solution for this:
this was "probably" my ip banned from themoviedb (even if i was able to manually query the api from the container)

as a workaround i've made the trafic go though a wireguard vpn bridge container


for others in my situation that's my working docker-compose.yml file (you still need to setup the vpn container image):

```
version: "3.7"
services:
  vpn:
    privileged: true
    build:
      # here you will have to replace by any wireguard container config, there is a lot of documentation available
      context: ./apps/vpn
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    sysctls:
      - "net.ipv4.conf.all.rp_filter=2"
      - "net.ipv6.conf.all.disable_ipv6=0"
    cap_add:
      - net_admin
      - sys_module
    network_mode: bridge
    ports:
      - 0.0.0.0:8096:8096
   jellyfin:
    image: jellyfin/jellyfin:10.8.9
    network_mode: service:vpn
    volumes:
    - /home/user/services/apps/jellyfin/config:/config
    - /home/user/services/apps/jellyfin/cache:/cache
    - /mnt/aiur:/media:ro
    restart: unless-stopped
    environment:
      TZ: Europe/Paris
    deploy:
      resources:
        reservations:
         devices:
         - capabilities: [gpu]
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
```


that fixes all the errors that i have ( even in the plugins sections )
