### ISSUE TITLE
[Issue]: Wrong files permission with docker-compose

### ISSUE THREAD

**Issue by zub0r** [jellyfin/jellyfin#9925]
### Please describe your bug

When custom user uid:guid is used in the default docker-compose file, some created files (logs) are owned by root, which causes errors with startup.
Manual chown is needed to change the owner to user to start up correctly.

### Jellyfin Version

10.8.z

### Environment

```markdown
- OS: Ubuntu 22.04.2
- Linux Kernel: 5.15.0-75
```

### Jellyfin logs

```shell
jellyfin  | Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/log' is denied.
jellyfin  |  ---> System.IO.IOException: Permission denied
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cvium** [comment]
Please upload your docker compose file (just the Jellyfin part)

**Comment by ivensfor** [comment]
I have encountered the same situation when installing Jellyfin in a Docker container on OpenWrt x86/64. The container failed to start up.

```
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /mnt/sdb1:/media
    restart: 'unless-stopped'
```

```
stderr: Unhandled Exception
stderr: System.UnauthorizedAccessException: Access to the path '/config/log' is denied.
stderr:  ---> System.IO.IOException: Permission denied
stderr:    --- End of inner exception stack trace ---
stderr:    at System.IO.FileSystem.CreateDirectory(String fullPath)
stderr:    at System.IO.Directory.CreateDirectory(String path)
stderr:    at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
stderr:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
stderr:    at Jellyfin.Server.Program.<Main>(String[] args)
stderr: Unhandled exception. System.UnauthorizedAccessException: Access to the path '/config/log' is denied.
stderr:  ---> System.IO.IOException: Permission denied
stderr:    --- End of inner exception stack trace ---
stderr:    at System.IO.FileSystem.CreateDirectory(String fullPath)
stderr:    at System.IO.Directory.CreateDirectory(String path)
stderr:    at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
stderr:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
stderr:    at Jellyfin.Server.Program.<Main>(String[] args)
```

**Comment by VitalyVaryvdin** [comment]
Running into the same issue

`docker-compose.yml`
```
version: '3.5'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    user: 1000:1000
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /srv/jellyfin/media:/media
    ports:
      - 8096:8096
    restart: 'unless-stopped'
```

`/srv/jellyfin` is owned by user and has 775 permissions
